[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "preptoolkit"
version = "0.1.0"
description = "Utilities for data prep and tooling"
authors = [{ name = "Yu Liu" }]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "tqdm",
    "psutil",
]

[tool.setuptools]
packages = ["MultiWrap", "DataImport"]

[project.urls]
Homepage = "https://github.com/BrainLiu1207/PrepToolkit.git"